export class Station {
    status;
    commune;
    nmarrond;
    name;
    bonus;
    bike_stands;
    number;
    availability;
    available_bike_stands;
    banking;
    pole;
    gid;
    available_bikes;
    code_insee;
    address;
    lat;
    lng;
    last_update_fme;
    last_update;
    address2;
    availabilitycode;
}